# Generated by Django 4.0.3 on 2022-06-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_tag_company_vote_total_review_company_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
