# Generated by Django 4.0.3 on 2022-06-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_vote_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='demo_link',
            new_name='website_link',
        ),
        migrations.RemoveField(
            model_name='company',
            name='source_link',
        ),
    ]
