# Generated by Django 4.0.5 on 2022-06-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_rename_title_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
